export const seratoFieldIds = {
  row: 1,
  fullPath: 2,
  location: 3,
  fileName: 4,
  title: 6,
  artist: 7,
  album: 8,
  genre: 9,
  length: 10,
  fileSize: 11,
  bitrate: 13,
  frequency: 14,
  bpm: 15,
  comments: 17,
  language: 18,
  grouping: 19,
  remixer: 20,
  label: 21,
  composer: 22,
  year: 23,
  startTime: 28,
  endTime: 29,
  deck: 31,
  preview: 39,
  playTime: 45,
  sessionId: 48,
  played: 50,
  key: 51,
  added: 52,
  updatedAt: 53,
  playerName: 63,
  commentName: 64,
  ejected: 70,
} as const;

export const seratoStringFields: ReadonlySet<number> = new Set([
  seratoFieldIds.fullPath,
  seratoFieldIds.location,
  seratoFieldIds.fileName,
  seratoFieldIds.title,
  seratoFieldIds.artist,
  seratoFieldIds.album,
  seratoFieldIds.genre,
  seratoFieldIds.length,
  seratoFieldIds.fileSize,
  seratoFieldIds.bitrate,
  seratoFieldIds.frequency,
  seratoFieldIds.comments,
  seratoFieldIds.grouping,
  seratoFieldIds.remixer,
  seratoFieldIds.label,
  seratoFieldIds.composer,
  seratoFieldIds.year,
  seratoFieldIds.key,
  seratoFieldIds.playerName,
  seratoFieldIds.commentName,
]);

export const seratoVersionString = "1.0/Serato Scratch LIVE Review";
