export const channels = {
  info: "joy:info",
  topicGet: "joy:topic:get",
  topicPush: "joy:topic:push",
  authPassword: "joy:auth:password",
  authBrowserBegin: "joy:auth:browser:begin",
  authBrowserCancel: "joy:auth:browser:cancel",
  authLogout: "joy:auth:logout",
  apiCall: "joy:api:call",
  commandRun: "joy:command:run",
  outboxRetry: "joy:outbox:retry",
  outboxDiscard: "joy:outbox:discard",
  sessionActivate: "joy:session:activate",
  realtimeSubscribe: "joy:rt:subscribe",
  realtimeUnsubscribe: "joy:rt:unsubscribe",
  realtimePush: "joy:rt:push",
  realtimeResync: "joy:rt:resync",
  settingsUpdate: "joy:settings:update",
  adaptersAdvance: "joy:adapters:advance",
  midiLoad: "joy:midi:load",
  midiSave: "joy:midi:save",
  stageOpen: "joy:stage:open",
  stageClose: "joy:stage:close",
  stageConfig: "joy:stage:config",
  stageDisplays: "joy:stage:displays",
  updatesCheck: "joy:updates:check",
  updatesInstall: "joy:updates:install",
  pickPath: "joy:system:pick",
  openExternal: "joy:system:external",
  menuCommand: "joy:menu:command",
} as const;

export const menuCommands = [
  "openSettings",
  "openPalette",
  "toggleBooth",
  "toggleLargeTargets",
  "toggleStage",
  "signOut",
  "endSession",
] as const;
export type MenuCommand = (typeof menuCommands)[number];
